CREATE TABLE [dbo].[Users] (
    [Seq N]         INT           IDENTITY (0, 1) NOT NULL,
    [User Name]     VARCHAR (256) NOT NULL,
    [Secret]        TEXT          NOT NULL,
    [Email]         VARCHAR (256) NOT NULL,
    [Name]          TEXT          NOT NULL,
    [Phone]         VARCHAR (10)  NOT NULL,
	[Date of birth] DATE          NOT NULL,
    [Gender]        VARCHAR (6)   NOT NULL,
    [City]          VARCHAR (50)  NOT NULL,
	[Address]       TEXT          NULL,
    [Account type]  VARCHAR (10)  NOT NULL,
    [Company name]  TEXT          NOT NULL,
    [Status]        TEXT          NULL,
    [Hobbies]       TEXT          NOT NULL,
    [Sec Q1]        TEXT          NOT NULL,
    [A1]            TEXT          NOT NULL,
    [Sec Q2]        TEXT          NOT NULL,
    [A2]            TEXT          NOT NULL,
    [More]          TEXT          NULL,
    PRIMARY KEY CLUSTERED ([Seq N] ASC),
    UNIQUE NONCLUSTERED ([Phone] ASC),
    UNIQUE NONCLUSTERED ([Email] ASC),
    UNIQUE NONCLUSTERED ([User Name] ASC)
);
